package life.majiang.community.mapper;

import java.util.List;
import life.majiang.community.model.User;
import life.majiang.community.model.UserExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_k
     *
     * @mbg.generated Sun Jun 16 16:39:56 GMT+08:00 2024
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_k
     *
     * @mbg.generated Sun Jun 16 16:39:56 GMT+08:00 2024
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_k
     *
     * @mbg.generated Sun Jun 16 16:39:56 GMT+08:00 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_k
     *
     * @mbg.generated Sun Jun 16 16:39:56 GMT+08:00 2024
     */
    int insert(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_k
     *
     * @mbg.generated Sun Jun 16 16:39:56 GMT+08:00 2024
     */
    int insertSelective(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_k
     *
     * @mbg.generated Sun Jun 16 16:39:56 GMT+08:00 2024
     */
    List<User> selectByExampleWithRowbounds(UserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_k
     *
     * @mbg.generated Sun Jun 16 16:39:56 GMT+08:00 2024
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_k
     *
     * @mbg.generated Sun Jun 16 16:39:56 GMT+08:00 2024
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_k
     *
     * @mbg.generated Sun Jun 16 16:39:56 GMT+08:00 2024
     */
    int updateByExampleSelective(@Param("row") User row, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_k
     *
     * @mbg.generated Sun Jun 16 16:39:56 GMT+08:00 2024
     */
    int updateByExample(@Param("row") User row, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_k
     *
     * @mbg.generated Sun Jun 16 16:39:56 GMT+08:00 2024
     */
    int updateByPrimaryKeySelective(User row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_k
     *
     * @mbg.generated Sun Jun 16 16:39:56 GMT+08:00 2024
     */
    int updateByPrimaryKey(User row);
}